### ISSUE TITLE
Empty flow service throws error in scanner 

### ISSUE THREAD

**Issue by omjee** [I8C/sonar-flow-plugin#15]
Language of file 'ns/MyPackage/testEmptyService/flow.xml' can not be decided as the file matches patterns of both sonar.lang.patterns.xml : **/*.xml,**/*.xsd,**/*.xsl and sonar.lang.patterns.flow : **/*.xml,**/*.ndf

**Comment by Samuelvdc** [comment]
Hi omjee 

Could you share sonar-project.properties and the complete flow.xml file. So we can reproduce the problem.?

Thx

**Comment by omjee** [comment]
ENV  webMethods Is 9.12 
Error:
13:24:22.847 ERROR: Error during SonarQube Scanner execution
Language of file 'ns/I8cFlowSonarPluginTest/flows/sendMail/flow.xml' can not be decided as the file matches patterns of both sonar.lang.patterns.xml : **/*.xml,**/*.xsd,**/*.xsl and sonar.lang.patterns.flow : **/*.xml,**/*.ndf

[Sonar flow issue.zip](https://github.com/I8C/sonar-flow-plugin/files/1215799/Sonar.flow.issue.zip)

attaching files

**Comment by Samuelvdc** [comment]
Thx Omjee, I could reproduce the issue. 
The problem is that both the SonarXML plugin and the Flow plugin offer xml analysis. 
You can specify the preferred language on a project basis. 

In the sonar-project.properties file of your flow project add following entry "sonar.language=flow"

**Comment by omjee** [comment]
Thank You, it worked, i will let you know if i stuck with any issue with big package, also nice reporting may increase usability. I am farmer SAG employee and have worked in Wm for quite a long time now :).   so far I loved it.

**Comment by Samuelvdc** [comment]
Great to hear! Yes we totally agree, a flow like visual representation inside of sonarqube for the rule violations could increase the usability a lot. We'll take a note of that and look into it!

**Comment by omjee** [comment]
its only doing flow services QA now? Does it do java services, adapter and other webMethods services?

**Comment by Samuelvdc** [comment]
For now only flow services are supported. The goal is however to cover as much as possible. 
So don't hesitate to also share your contributions :) 
Subscribe to the project and we'll keep you up to date if more features will be added
