### ISSUE TITLE
False positive for empty map step

### ISSUE THREAD

**Issue by freichwein** [I8C/sonar-flow-plugin#16]
Hi,
we get a false positive response by the empty map rule. 
I attached an example flow service. This flow service contains a map step where a variable is set to a hardcoded value. This map step is reported as a empty map step.
Can you reproduce this issue?
[FRE.zip](https://github.com/I8C/sonar-flow-plugin/files/1531776/FRE.zip)

**Comment by dewanst** [comment]
Hi @freichwein 

I was able to reproduce it, and it looks quite straightforward to fix it. I will keep you updated.

Grtz

**Comment by dewanst** [comment]
Hi @freichwein 
Could you check if branch 16_emptyMap works for you?

**Comment by freichwein** [comment]
Hi @dewanst 
The branch is working. Thanks a lot.
The file "src/test/resources/WmPackage/ns/I8cFlowSonarPluginTest/pub/checkEmptyMapValid/flow.xml" is missing for the test case.
